server.port: 8181 # Server HTTP port.
# Acquire port
com.cmos.acquire:
    #disable  dataServer and dataHandler .if set this value true,neither dataServer nor dataHandler will work
    disabled: false
   #data server listen on this port
    port: 8001

#RocketMQ server info
com.cmos.mq:
    ProducerGroupName: ProducerGroupName
    nameServerAddress: 192.168.100.86:28881
    instanceName: Producer
# Spring settings
spring:
    profiles.active: dev
    datasource:
        max-active: 100
        max-idle: 40
        min-idle: 35
        url: jdbc:mysql://192.168.100.126:50000/ipg_sit?useUnicode=true&characterEncoding=utf8&useSSL=false
#        username: ipg_dev
#        password: mysql*2016#720
        username: ipg_sit
        #password: yMq6k%sx
        password: eU1xNmslc3g=
    jpa:
        show-sql: true
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            properties:
                hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    redis:
        host: 192.168.100.66
        port: 6379
        password:
        database: 0
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
# Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
    level:
        org.hibernate: WARN
        org.springframework: WARN
    file: ipg.log

